#requires -Version 5.1
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [hashtable]$Config
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$secretDir = Join-Path $repoRoot 'secrets'
$envFile = Join-Path $secretDir '.env'

New-Item -ItemType Directory -Path $secretDir -Force | Out-Null

if (Test-Path $envFile) {
    Write-Warning "Secrets file already exists: $envFile"
    Write-Warning 'Existing secrets were not overwritten.'
    return
}

$lines = @(
    '# Local-only API credentials. NEVER COMMIT THIS FILE.',
    '# Generated by scripts/Initialize-Secrets.ps1'
)

foreach ($name in $Config.ThreatIntelEnvironmentVariables) {
    $secure = Read-Host "Enter $name (leave blank to configure later)" -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
        $escaped = $plain.Replace('"', '\"')
        $lines += "$name=\"$escaped\""
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

[IO.File]::WriteAllLines($envFile, $lines, [Text.UTF8Encoding]::new($false))
Write-Host "Created local secrets file: $envFile" -ForegroundColor Green
Write-Host 'The repository .gitignore excludes secrets/ and .env files.' -ForegroundColor Cyan
